blank_issues_enabled: false
contact_links:
  - name: 💾 Träwelling FAQ
    url: https://help.traewelling.de
    about: If you have questions regarding the in-app timetable data or journey routing, please
      check whether your question has been answered in the Träwelling FAQ.
