name: build

on:
  pull_request:
    branches:
      - main
      - dev
  push:
    tags:
      - 'v*'

jobs:
  assemble:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Assemble foss flavor
        run: ./gradlew assembleFossDebug
      - name: Assemble Google Play flavor
        run: ./gradlew assemblePlayDebug

      - name: ls
        run: ls /home/runner/work/traewelldroid/traewelldroid/build/outputs/apk
      
      - name: ls
        run: ls /home/runner/work/traewelldroid/traewelldroid/
        
      - uses: vimtor/action-zip@v1
        with:
          files: /home/runner/work/traewelldroid/traewelldroid/build/outputs/apk
          dest: assembly.zip
          
      - uses: actions/upload-artifact@v3
        with: 
          name: assembly
          path: assembly.zip
